### ISSUE TITLE
WSL 환경에서 nGrinder Controller에 외부 PC에서 agent 접속 이슈

### ISSUE THREAD

**Issue by choi3179** [be01-4nd-mini-project-TEAM1/R3-nGrinder#1]
### nGrinder agent가 Controller에 연결되지 않는다.
- https://github.com/naver/ngrinder/wiki/Installation-Guide
- nGrinder Controller port-forwarding
```sh
// 윈도우 cmd를 관리자로 실행
$ netsh interface portproxy add v4tov4 listenport=8080 listenaddress=0.0.0.0 connectport=8080 connectaddress=172.31.65.42
$ netsh interface portproxy show v4tov4

ipv4 수신 대기:             ipv4에 연결:

주소            포트        주소            포트
--------------- ----------  --------------- ----------
0.0.0.0         8080        172.31.65.42    8080

```
- agent.conf
```sh
$ pwd
~/.ngrinder_agent
$ cat agent.conf
common.start_mode=agent
agent.controller_host=192.168.0.43
agent.controller_port=16001
agent.subregion=
agent.owner=
```
- 사설 ip의 8080 port로 nGrinder Controller 화면에는 접근할 수 있으나 agent는 접속되지 않았다.
```sh
$ ./run_agent.sh
```
![image](https://github.com/be01-4nd-mini-project-TEAM1/R3-nGrinder/assets/66417882/d9be8031-7ddc-4351-9af5-f05698751c4a)

**Comment by choi3179** [comment]
## Solution
- nGrinder agent는 기본적으로 16001번 포트를 이용한다.
- 포트 포워딩으로 nGrinder Controller에 접속할 수 있도록 하듯이 agent가 접속하기 위한 포트포워딩이 추가적으로 필요하다.
```
// 윈도우 cmd를 관리자로 실행
$ netsh interface portproxy add v4tov4 listenport=16001 listenaddress=0.0.0.0 connectport=16001 connectaddress=172.31.65.42
netsh interface portproxy show v4tov4

ipv4 수신 대기:             ipv4에 연결:

주소            포트        주소            포트
--------------- ----------  --------------- ----------
0.0.0.0         8080        172.31.65.42    8080
0.0.0.0         16001       172.31.65.42    16001
```  
### 결과
![image](https://github.com/be01-4nd-mini-project-TEAM1/R3-nGrinder/assets/66417882/146e42fc-2987-481f-b3be-73b89bfa01f4)

**Comment by choi3179** [comment]
## 윈도우 방화벽 설정
### 외부에서 사설 ip의 특정 포트로 접속할 수 있도록 포트를 열어준다.
- 방화벽 및 네트워크 보호 > 고급 설정
![image](https://github.com/be01-4nd-mini-project-TEAM1/R3-nGrinder/assets/66417882/507fc344-210e-4cfe-92f7-43ff82a132db)

- 인바운드 규칙 > 새 규칙
![image](https://github.com/be01-4nd-mini-project-TEAM1/R3-nGrinder/assets/66417882/fef81e85-8ca8-4d5f-b6da-de2585486079)

- 포트 > [오픈할 포트 입력] > [연결 허용] > [제약사항 지정] > [이름 지정] > 저장
![image](https://github.com/be01-4nd-mini-project-TEAM1/R3-nGrinder/assets/66417882/f68ad537-c732-4d46-97f2-34b147a76b42)
![image](https://github.com/be01-4nd-mini-project-TEAM1/R3-nGrinder/assets/66417882/6c8a63ac-7e00-454b-80d6-abb2b61e29c5)
![image](https://github.com/be01-4nd-mini-project-TEAM1/R3-nGrinder/assets/66417882/ad296b38-d717-47d1-82ed-af4d8322b785)

**Comment by Jaelinny** [comment]
![LGTM](https://i.lgtm.fun/2pd6.gif)
